### ISSUE TITLE
Replace steemdata

### ISSUE THREAD

**Issue by dittaeva** [svk31/steem-cointracking#1]
[Steemdata was shut down on the 1st of May](https://steemit.com/steemdata/@furion/steemdata-is-shutting-down-on-may-1st). Alternatives are mentioned in the article and comments. Any chance it can be updated?

**Comment by svk31** [comment]
Yea unfortunately I didn't realize steemdata was being shutdown, and as far as I can tell there aren't any viable alternatives.

One option is running a local version of steemdata yourself, which is fairly easy to do.

**Comment by dittaeva** [comment]
I see... I think I'll go for [steemreports](http://www.steemreports.com/accounts-reporting-tool/) and a spreadsheet this time around.
